// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiOtIB8X8l6Wfeg-LlvU9cTmCeEguem4c',
    appId: '1:366730116086:web:39226cae972689dc80e5d7',
    messagingSenderId: '366730116086',
    projectId: 'antialergi-2f0c2',
    authDomain: 'antialergi-2f0c2.firebaseapp.com',
    storageBucket: 'antialergi-2f0c2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBULFGuodMMxxWHA3pnxCFQM31bXIOCQiw',
    appId: '1:366730116086:android:3e1f5907865634c980e5d7',
    messagingSenderId: '366730116086',
    projectId: 'antialergi-2f0c2',
    storageBucket: 'antialergi-2f0c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDIB69FNEIHvYDYBZqr2JAn3KoaYYFCJk',
    appId: '1:366730116086:ios:f11992af462a6ee880e5d7',
    messagingSenderId: '366730116086',
    projectId: 'antialergi-2f0c2',
    storageBucket: 'antialergi-2f0c2.firebasestorage.app',
    iosBundleId: 'com.example.antialergi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDIB69FNEIHvYDYBZqr2JAn3KoaYYFCJk',
    appId: '1:366730116086:ios:f11992af462a6ee880e5d7',
    messagingSenderId: '366730116086',
    projectId: 'antialergi-2f0c2',
    storageBucket: 'antialergi-2f0c2.firebasestorage.app',
    iosBundleId: 'com.example.antialergi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiOtIB8X8l6Wfeg-LlvU9cTmCeEguem4c',
    appId: '1:366730116086:web:7a2edbcfd2ceaa6580e5d7',
    messagingSenderId: '366730116086',
    projectId: 'antialergi-2f0c2',
    authDomain: 'antialergi-2f0c2.firebaseapp.com',
    storageBucket: 'antialergi-2f0c2.firebasestorage.app',
  );
}
